### ISSUE TITLE
Open-source json-sequence

### ISSUE THREAD

**Issue by mdub** [greensync/json-sequence#5]
We've resolved that it would make our lives a whole lot simpler if this was open-source. 

Not to mention all the other good reasons for open-sourcing things.

Any objections, @khaong?

**Comment by mdub** [comment]
I've made the repo public.

**Comment by mdub** [comment]
I've published `v0.1.2` to RubyGems.org:

```
$ be rake release
json-sequence 0.1.2 built to pkg/json-sequence-0.1.2.gem.
Tag v0.1.2 has already been created.
Pushed json-sequence 0.1.2 to rubygems.org
```

**Comment by jaischeema** [comment]
Wooohoo 🚢

**Comment by ZimbiX** [comment]
Nice :+1: I've just audited the commits, PRs and issues to make sure there was nothing confidential released

**Comment by mdub** [comment]
@jaischeema and I are gem "owners" (so can push). I'm not feeling the urgent need to create a build/release pipeline right now, as this is essentially "done".
